### ISSUE TITLE
BUG: Error at start the module lspconfig/configs not exists

### ISSUE THREAD

**Issue by TeoDev1611** [nazo6/lspinstall.nvim#3]
Hi thanks for make this amazing plugin but i have a Bug when i trying use this 

![image](https://user-images.githubusercontent.com/73144037/130688158-5de80ed1-2caf-451a-bb01-d8d7437e8b15.png)

Not found the module lspconfig/configs here are my packer installation:
```lua
use {
  'neovim/nvim-lspconfig',
  config = function()
    require 'lsp.lsp-servers'
  end,
  --event = 'BufReadPre',
}

use {
  'nazo6/lspinstall.nvim',
  config = function()
    require('lsp.installer')
  end,
}
```

Any idea for fix that?

**Comment by barungh** [comment]
> Hi thanks for make this amazing plugin but i have a Bug when i trying use this
> 
> ![image](https://user-images.githubusercontent.com/73144037/130688158-5de80ed1-2caf-451a-bb01-d8d7437e8b15.png)
> 
> Not found the module lspconfig/configs here are my packer installation:
> 
> ```lua
> use {
>   'neovim/nvim-lspconfig',
>   config = function()
>     require 'lsp.lsp-servers'
>   end,
>   --event = 'BufReadPre',
> }
> 
> use {
>   'nazo6/lspinstall.nvim',
>   config = function()
>     require('lsp.installer')
>   end,
> }
> ```
> 
> Any idea for fix that?

![image](https://user-images.githubusercontent.com/12285528/130700113-b600b668-25f8-458e-b8b0-438deb53a68c.png)

hey,

with [NvChad](https://github.com/NvChad/NvChad) config , this is what I am doing,

on my first run I also got the same error , 
may be because it is lazy loaded so dependency plugins are not found

but after that never saw that error

mind it, I just commented out `kabouzeid/nvim-lspinstall` and added this one

then of course, `:packer sync` which removes previous plugin directory 

Of course I created a file `nvim/lua/plugins/configs/nazolsp.lua` and put the [settings](https://github.com/nazo6/lspinstall.nvim#settings)
 
![image](https://user-images.githubusercontent.com/12285528/130701112-cce7e7f7-5d51-46e6-b206-51c050df8e63.png)

**Comment by TeoDev1611** [comment]
I make that but not work ☹️

**Comment by barungh** [comment]
> I make that but not work ☹️

Can you post screenshot of your config ?

**Comment by nazo6** [comment]
I couldn't reproduce it. Can you give me the minimum configuration that can be reproduced?

**Comment by TeoDev1611** [comment]
> > I make that but not work ☹️
> 
> Can you post screenshot of your config ?

Config of lspinstall.nvim?

**Comment by TeoDev1611** [comment]
> I couldn't reproduce it. Can you give me the minimum configuration that can be reproduced?

The configuration of the README is what I'm using

**Comment by Borwe** [comment]
> The configuration of the README is what I'm using

True, I installed cmake, and found out it didn't work also, same errors.

**Comment by nazo6** [comment]
I rewrote plugin. Please try it.
